### ISSUE TITLE
Blobs

### ISSUE THREAD

**Issue by stevenxxiu** [dumbmatter/realistic-structured-clone#3]
I'm looking at using fake-indexeddb for faster unit testing.

Upon reading the w3c spec, could the blob implementation be just `new Blob([blob])`? On mdn it doesn't appear that `close()` is implemented in any browser. Blobs are also immutable so copying the real underlying data isn't necessary. Any thoughts?

**Comment by dumbmatter** [comment]
You could be right, I don't know too much about how blobs work, but I'll look into it some time in the next couple days. Or if you're confident in your solution and want to send a PR before then, feel free :)

**Comment by dumbmatter** [comment]
Resolved by PR #4, will release new version soon
